-- =====================================================================
-- OPORTUNIDADES — nomes em português (Kevin, 08/10/2026)
-- As datas internacionais vinham das fontes (ONU e agências) com o nome
-- em inglês. Aqui só o NOME exibido muda:
--   • nome            → em português;
--   • aliases         → ganha o nome original em inglês (a busca e a
--                       sincronização continuam achando a data por ele);
--   • chave           → NÃO muda (é por ela e pela referência da fonte
--                       que a sincronização semanal reconhece a data, e a
--                       sincronização nunca regrava o nome).
-- Nenhuma data, categoria, tag, vínculo ou relevância é alterada à mão.
-- Só mexe em oportunidade ativa cujo nome ainda é exatamente o inglês
-- da lista; rodar de novo não faz nada.
-- Para desfazer uma: o nome original está em aliases.
-- =====================================================================
with t(en, pt) as (values
  ('World Braille Day', 'Dia Mundial do Braille'),
  ('International Day of Education', 'Dia Internacional da Educação'),
  ('International Day of Clean Energy', 'Dia Internacional da Energia Limpa'),
  ('International Day of Commemoration in Memory of the Victims of the Holocaust', 'Dia Internacional em Memória das Vítimas do Holocausto'),
  ('World Leprosy Day', 'Dia Mundial de Combate à Hanseníase'),
  ('World Interfaith Harmony Week, 1-7 February', 'Semana Mundial da Harmonia Inter-religiosa (1 a 7 de fevereiro)'),
  ('World Wetlands Day', 'Dia Mundial das Zonas Úmidas'),
  ('International Day of Human Fraternity', 'Dia Internacional da Fraternidade Humana'),
  ('International Day of Zero Tolerance to Female Genital Mutilation', 'Dia Internacional da Tolerância Zero à Mutilação Genital Feminina'),
  ('International Day of the Arabian Leopard', 'Dia Internacional do Leopardo-da-Arábia'),
  ('World Pulses Day [FAO]', 'Dia Mundial das Leguminosas'),
  ('International Day of Women and Girls in Science', 'Dia Internacional das Mulheres e Meninas na Ciência'),
  ('International Day for the Prevention of Violent Extremism as and when Conducive to Terrorism', 'Dia Internacional para a Prevenção do Extremismo Violento que Conduz ao Terrorismo'),
  ('World Radio Day', 'Dia Mundial do Rádio'),
  ('Global Tourism Resilience Day', 'Dia Mundial da Resiliência do Turismo'),
  ('World Day of Social Justice', 'Dia Mundial da Justiça Social'),
  ('International Mother Language Day', 'Dia Internacional da Língua Materna'),
  ('World Seagrass Day', 'Dia Mundial das Pradarias Marinhas'),
  ('Zero Discrimination Day [UNAIDS]', 'Dia Mundial de Zero Discriminação'),
  ('World Wildlife Day', 'Dia Mundial da Vida Selvagem'),
  ('International Day for Disarmament and Non-Proliferation Awareness', 'Dia Internacional de Conscientização sobre Desarmamento e Não Proliferação'),
  ('International Women''s Day', 'Dia Internacional da Mulher'),
  ('International Day of Women Judges', 'Dia Internacional das Mulheres Juízas'),
  ('International Day to Combat Islamophobia', 'Dia Internacional de Combate à Islamofobia'),
  ('French Language Day', 'Dia da Língua Francesa'),
  ('International Day of Happiness', 'Dia Internacional da Felicidade'),
  ('International Day for the Elimination of Racial Discrimination', 'Dia Internacional pela Eliminação da Discriminação Racial'),
  ('International Day of Nowruz', 'Dia Internacional do Nowruz'),
  ('World Poetry Day [UNESCO]', 'Dia Mundial da Poesia'),
  ('World Meteorological Day [WMO]', 'Dia Meteorológico Mundial'),
  ('International Day for the Right to the Truth concerning Gross Human Rights Violations and for the Dignity of Victims', 'Dia Internacional pelo Direito à Verdade sobre Graves Violações dos Direitos Humanos e pela Dignidade das Vítimas'),
  ('International Day of Remembrance of the Victims of Slavery and the Transatlantic Slave Trade', 'Dia Internacional em Memória das Vítimas da Escravidão e do Tráfico Transatlântico de Escravizados'),
  ('International Day of Solidarity with Detained and Missing Staff Members', 'Dia Internacional de Solidariedade com os Funcionários Detidos e Desaparecidos'),
  ('International Day of Zero Waste', 'Dia Internacional do Lixo Zero'),
  ('International Day for Mine Awareness and Assistance in Mine Action', 'Dia Internacional de Conscientização sobre Minas e de Assistência à Ação contra Minas'),
  ('International Day of Conscience', 'Dia Internacional da Consciência'),
  ('International Day of Sport for Development and Peace', 'Dia Internacional do Esporte para o Desenvolvimento e a Paz'),
  ('International Day of Reflection on the 1994 Genocide against the Tutsi in Rwanda', 'Dia Internacional de Reflexão sobre o Genocídio de 1994 contra os Tutsis em Ruanda'),
  ('International Day of Human Space Flight', 'Dia Internacional do Voo Espacial Tripulado'),
  ('Chinese Language Day', 'Dia da Língua Chinesa'),
  ('World Creativity and Innovation Day', 'Dia Mundial da Criatividade e Inovação'),
  ('International Mother Earth Day', 'Dia Internacional da Mãe Terra'),
  ('English Language Day', 'Dia da Língua Inglesa'),
  ('Spanish Language Day', 'Dia da Língua Espanhola'),
  ('World Book and Copyright Day [UNESCO]', 'Dia Mundial do Livro e do Direito Autoral'),
  ('International Day of Multilateralism and Diplomacy for Peace', 'Dia Internacional do Multilateralismo e da Diplomacia pela Paz'),
  ('International Delegate’s Day', 'Dia Internacional do Delegado'),
  ('International Chernobyl Disaster Remembrance Day', 'Dia Internacional em Memória do Desastre de Chernobyl'),
  ('World Intellectual Property Day [WIPO]', 'Dia Mundial da Propriedade Intelectual'),
  ('World Day for Safety and Health at Work', 'Dia Mundial da Segurança e Saúde no Trabalho'),
  ('International Jazz Day', 'Dia Internacional do Jazz'),
  ('Vesak, the Day of the Full Moon', 'Vesak, o Dia da Lua Cheia'),
  ('World Tuna Day', 'Dia Mundial do Atum'),
  ('World Press Freedom Day', 'Dia Mundial da Liberdade de Imprensa'),
  ('World Hand Hygiene Day', 'Dia Mundial da Higiene das Mãos'),
  ('World Portuguese Language Day [UNESCO]', 'Dia Mundial da Língua Portuguesa'),
  ('Time of Remembrance and Reconciliation for Those Who Lost Their Lives During the Second World War', 'Dias de Memória e Reconciliação pelos que Perderam a Vida na Segunda Guerra Mundial'),
  ('International Day of Argania', 'Dia Internacional da Argânia'),
  ('International Day of Plant Health [FAO]', 'Dia Internacional da Sanidade Vegetal'),
  ('International Day of Families', 'Dia Internacional das Famílias'),
  ('International Day of Light [UNESCO]', 'Dia Internacional da Luz'),
  ('International Day of Living Together in Peace', 'Dia Internacional da Convivência em Paz'),
  ('World Telecommunication and Information Society Day', 'Dia Mundial das Telecomunicações e da Sociedade da Informação'),
  ('World Fair Play Day', 'Dia Mundial do Fair Play'),
  ('World Bee Day [FAO]', 'Dia Mundial das Abelhas'),
  ('International Tea Day [FAO]', 'Dia Internacional do Chá'),
  ('World Day for Cultural Diversity for Dialogue and Development', 'Dia Mundial da Diversidade Cultural para o Diálogo e o Desenvolvimento'),
  ('International Day for Biological Diversity', 'Dia Internacional da Diversidade Biológica'),
  ('International Day to End Obstetric Fistula', 'Dia Internacional pelo Fim da Fístula Obstétrica'),
  ('International Day of the Markhor', 'Dia Internacional do Markhor'),
  ('Week of Solidarity with the Peoples of Non-Self-Governing Territories, 25-31 May', 'Semana de Solidariedade com os Povos dos Territórios Não Autônomos (25 a 31 de maio)'),
  ('World Football Day', 'Dia Mundial do Futebol'),
  ('International Day of UN Peacekeepers', 'Dia Internacional dos Soldados da Paz das Nações Unidas'),
  ('International Day of Potato [FAO]', 'Dia Internacional da Batata'),
  ('Global Day of Parents', 'Dia Mundial dos Pais e Mães'),
  ('World Bicycle Day', 'Dia Mundial da Bicicleta'),
  ('International Day of Innocent Children Victims of Aggression', 'Dia Internacional das Crianças Inocentes Vítimas de Agressão'),
  ('International Day for the Fight against Illegal, Unreported and Unregulated Fishing', 'Dia Internacional de Combate à Pesca Ilegal, Não Declarada e Não Regulamentada'),
  ('World Environment Day', 'Dia Mundial do Meio Ambiente'),
  ('Russian Language Day', 'Dia da Língua Russa'),
  ('World Food Safety Day', 'Dia Mundial da Segurança dos Alimentos'),
  ('World Oceans Day', 'Dia Mundial dos Oceanos'),
  ('International Day for Dialogue among Civilizations', 'Dia Internacional do Diálogo entre Civilizações'),
  ('International Day of Play', 'Dia Internacional do Brincar'),
  ('World Day Against Child Labour', 'Dia Mundial contra o Trabalho Infantil'),
  ('World Elder Abuse Awareness Day', 'Dia Mundial de Conscientização da Violência contra a Pessoa Idosa'),
  ('International Day of Family Remittances', 'Dia Internacional das Remessas Familiares'),
  ('World Day to Combat Desertification and Drought', 'Dia Mundial de Combate à Desertificação e à Seca'),
  ('International Day for Countering Hate Speech', 'Dia Internacional de Combate ao Discurso de Ódio'),
  ('Sustainable Gastronomy Day [FAO]', 'Dia da Gastronomia Sustentável'),
  ('International Day for the Elimination of Sexual Violence in Conflict', 'Dia Internacional pela Eliminação da Violência Sexual em Conflitos'),
  ('World Refugee Day', 'Dia Mundial do Refugiado'),
  ('International Day of the Celebration of the Solstice', 'Dia Internacional da Celebração do Solstício'),
  ('International Day of Yoga', 'Dia Internacional do Yoga'),
  ('International Widows'' Day', 'Dia Internacional das Viúvas'),
  ('United Nations Public Service Day', 'Dia do Serviço Público das Nações Unidas'),
  ('International Day of Women in Diplomacy', 'Dia Internacional das Mulheres na Diplomacia'),
  ('Day of the Seafarer [IMO]', 'Dia do Marítimo'),
  ('International Day against Drug Abuse and Illicit Trafficking', 'Dia Internacional contra o Abuso e o Tráfico Ilícito de Drogas'),
  ('United Nations International Day in Support of Victims of Torture', 'Dia Internacional de Apoio às Vítimas de Tortura'),
  ('Micro-, Small and Medium-sized Enterprises Day', 'Dia das Micro, Pequenas e Médias Empresas'),
  ('International Day of the Tropics', 'Dia Internacional dos Trópicos'),
  ('International Asteroid Day', 'Dia Internacional do Asteroide'),
  ('International Day of Parliamentarism', 'Dia Internacional do Parlamentarismo'),
  ('World Kiswahili Language Day', 'Dia Mundial da Língua Suaíli'),
  ('International Day of Reflection and Commemoration of the 1995 Genocide in Srebrenica', 'Dia Internacional de Reflexão e Memória do Genocídio de 1995 em Srebrenica'),
  ('World Population Day', 'Dia Mundial da População'),
  ('International Day of Combating Sand and Dust Storms', 'Dia Internacional de Combate às Tempestades de Areia e Poeira'),
  ('World Youth Skills Day', 'Dia Mundial das Habilidades dos Jovens'),
  ('Nelson Mandela International Day', 'Dia Internacional Nelson Mandela'),
  ('International Moon Day', 'Dia Internacional da Lua'),
  ('World Chess Day', 'Dia Mundial do Xadrez'),
  ('International Day of Women and Girls of African Descent', 'Dia Internacional das Mulheres e Meninas Afrodescendentes'),
  ('International Day of Friendship', 'Dia Internacional da Amizade'),
  ('World Day against Trafficking in Persons', 'Dia Mundial contra o Tráfico de Pessoas'),
  ('World Steelpan Day', 'Dia Mundial do Steelpan'),
  ('International Youth Day', 'Dia Internacional da Juventude'),
  ('World Humanitarian Day', 'Dia Mundial Humanitário'),
  ('International Day of Remembrance and Tribute to the Victims of Terrorism', 'Dia Internacional de Memória e Homenagem às Vítimas do Terrorismo'),
  ('International Day Commemorating the Victims of Acts of Violence Based on Religion or Belief', 'Dia Internacional em Memória das Vítimas de Violência Baseada em Religião ou Crença'),
  ('International Day for the Remembrance of the Slave Trade and Its Abolition [UNESCO]', 'Dia Internacional em Memória do Tráfico de Escravizados e de sua Abolição'),
  ('World Lake Day', 'Dia Mundial dos Lagos'),
  ('International Day against Nuclear Tests', 'Dia Internacional contra os Testes Nucleares'),
  ('International Day of the Victims of Enforced Disappearances', 'Dia Internacional das Vítimas de Desaparecimentos Forçados'),
  ('International Day for People of African Descent', 'Dia Internacional das Pessoas Afrodescendentes'),
  ('International Day of Charity', 'Dia Internacional da Caridade'),
  ('International Day of Clean Air for Blue Skies [UNEP]', 'Dia Internacional do Ar Limpo para um Céu Azul'),
  ('International Day of Police Cooperation', 'Dia Internacional da Cooperação Policial'),
  ('World Duchenne Awareness Day', 'Dia Mundial de Conscientização sobre a Distrofia de Duchenne'),
  ('International Literacy Day [UNESCO]', 'Dia Internacional da Alfabetização'),
  ('International Day to Protect Education from Attack', 'Dia Internacional para Proteger a Educação de Ataques'),
  ('United Nations Day for South-South Cooperation', 'Dia das Nações Unidas para a Cooperação Sul-Sul'),
  ('International Day of Democracy', 'Dia Internacional da Democracia'),
  ('International Day for Interventional Cardiology', 'Dia Internacional da Cardiologia Intervencionista'),
  ('International Day for the Preservation of the Ozone Layer', 'Dia Internacional para a Preservação da Camada de Ozônio'),
  ('International Day of Science, Technology and Innovation for the South', 'Dia Internacional da Ciência, Tecnologia e Inovação para o Sul'),
  ('International Equal Pay Day', 'Dia Internacional da Igualdade Salarial'),
  ('World Cleanup Day', 'Dia Mundial da Limpeza'),
  ('International Day of Peace', 'Dia Internacional da Paz'),
  ('International Day for the Total Elimination of Nuclear Weapons', 'Dia Internacional pela Eliminação Total das Armas Nucleares'),
  ('World Tourism Day [UN Tourism]', 'Dia Mundial do Turismo'),
  ('International Day for Universal Access to Information', 'Dia Internacional do Acesso Universal à Informação'),
  ('World Rabies Day', 'Dia Mundial contra a Raiva'),
  ('International Day of Awareness of Food Loss and Waste [FAO]', 'Dia Internacional de Conscientização sobre Perdas e Desperdício de Alimentos'),
  ('International Translation Day', 'Dia Internacional da Tradução'),
  ('International Day of Older Persons', 'Dia Internacional da Pessoa Idosa'),
  ('International Day of Non-Violence', 'Dia Internacional da Não Violência'),
  ('World Space Week, 4-10 October', 'Semana Mundial do Espaço (4 a 10 de outubro)'),
  ('World Teachers’ Day [UNESCO]', 'Dia Mundial dos Professores'),
  ('World Cotton Day', 'Dia Mundial do Algodão'),
  ('World Post Day', 'Dia Mundial dos Correios'),
  ('International Day of the Girl Child', 'Dia Internacional da Menina'),
  ('International Day for Disaster Risk Reduction', 'Dia Internacional para a Redução do Risco de Desastres'),
  ('International Day of Rural Women', 'Dia Internacional das Mulheres Rurais'),
  ('World Food Day [FAO]', 'Dia Mundial da Alimentação'),
  ('International Day for the Eradication of Poverty', 'Dia Internacional para a Erradicação da Pobreza'),
  ('International lead poisoning prevention week of action', 'Semana Internacional de Prevenção da Intoxicação por Chumbo'),
  ('International Day of the Snow Leopard', 'Dia Internacional do Leopardo-das-Neves'),
  ('Disarmament Week, 24-30 October', 'Semana do Desarmamento (24 a 30 de outubro)'),
  ('Global Media and Information Literacy Week, 24-31 October', 'Semana Mundial da Alfabetização Midiática e Informacional (24 a 31 de outubro)'),
  ('United Nations Day', 'Dia das Nações Unidas'),
  ('World Development Information Day', 'Dia Mundial da Informação sobre o Desenvolvimento'),
  ('World Day for Audiovisual Heritage [UNESCO]', 'Dia Mundial do Patrimônio Audiovisual'),
  ('International Day of Care and Support', 'Dia Internacional do Cuidado e do Apoio'),
  ('World Cities Day', 'Dia Mundial das Cidades'),
  ('International Day to End Impunity for Crimes against Journalists', 'Dia Internacional pelo Fim da Impunidade dos Crimes contra Jornalistas'),
  ('World Tsunami Awareness Day', 'Dia Mundial de Conscientização sobre Tsunamis'),
  ('International Day for Preventing the Exploitation of the Environment in War and Armed Conflict', 'Dia Internacional para a Prevenção da Exploração do Meio Ambiente em Guerras e Conflitos Armados'),
  ('International Week of Science and Peace, 9-15 November', 'Semana Internacional da Ciência e da Paz (9 a 15 de novembro)'),
  ('World Science Day for Peace and Development', 'Dia Mundial da Ciência pela Paz e pelo Desenvolvimento'),
  ('World Diabetes Day', 'Dia Mundial do Diabetes'),
  ('International Day for the Prevention of and Fight against All Forms of Transnational Organized Crime', 'Dia Internacional de Prevenção e Combate ao Crime Organizado Transnacional'),
  ('International Day for Tolerance [UNESCO]', 'Dia Internacional da Tolerância'),
  ('World Day for the Prevention of and Healing from Child Sexual Exploitation, Abuse and Violence', 'Dia Mundial de Prevenção e Reparação da Exploração, do Abuso e da Violência Sexual contra Crianças'),
  ('World Toilet Day', 'Dia Mundial do Banheiro'),
  ('Africa Industrialization Day', 'Dia da Industrialização da África'),
  ('World Children''s Day', 'Dia Universal da Criança'),
  ('World Philosophy Day [UNESCO]', 'Dia Mundial da Filosofia'),
  ('World Television Day', 'Dia Mundial da Televisão'),
  ('World Conjoined Twins Day', 'Dia Mundial dos Gêmeos Siameses'),
  ('International Day for the Elimination of Violence against Women', 'Dia Internacional pela Eliminação da Violência contra as Mulheres'),
  ('World Sustainable Transport Day', 'Dia Mundial do Transporte Sustentável'),
  ('International Day of Solidarity with the Palestinian People', 'Dia Internacional de Solidariedade com o Povo Palestino'),
  ('Day of Remembrance for all Victims of Chemical Warfare', 'Dia em Memória de Todas as Vítimas da Guerra Química'),
  ('International Day for the Abolition of Slavery', 'Dia Internacional para a Abolição da Escravidão'),
  ('International Day of Banks', 'Dia Internacional dos Bancos'),
  ('International Volunteer Day for Economic and Social Development', 'Dia Internacional do Voluntariado'),
  ('World Soil Day', 'Dia Mundial do Solo'),
  ('International Civil Aviation Day', 'Dia Internacional da Aviação Civil'),
  ('International Anti-Corruption Day', 'Dia Internacional contra a Corrupção'),
  ('International Day of Commemoration and Dignity of the Victims of the Crime of Genocide and of the Prevention of this Crime', 'Dia Internacional em Memória e pela Dignidade das Vítimas do Crime de Genocídio e pela Prevenção desse Crime'),
  ('Human Rights Day', 'Dia dos Direitos Humanos'),
  ('International Mountain Day', 'Dia Internacional das Montanhas'),
  ('International Day of Neutrality', 'Dia Internacional da Neutralidade'),
  ('Universal Health Coverage Day', 'Dia da Cobertura Universal de Saúde'),
  ('Arabic Language Day', 'Dia da Língua Árabe'),
  ('International Migrants Day', 'Dia Internacional dos Migrantes'),
  ('International Human Solidarity Day', 'Dia Internacional da Solidariedade Humana'),
  ('World Basketball Day', 'Dia Mundial do Basquete'),
  ('World Meditation Day', 'Dia Mundial da Meditação'),
  ('International Anti-Cybercrime Day', 'Dia Internacional contra o Cibercrime'),
  ('International Coffee Day', 'Dia Internacional do Café'),
  ('International Day against Colonialism in All its Forms and Manifestations', 'Dia Internacional contra o Colonialismo em Todas as suas Formas e Manifestações'),
  ('International Day Against Unilateral Coercive Measures', 'Dia Internacional contra as Medidas Coercitivas Unilaterais'),
  ('International Day for Judicial Well-being', 'Dia Internacional do Bem-Estar Judicial'),
  ('International Day in Memory of the Victims of Earthquakes', 'Dia Internacional em Memória das Vítimas de Terremotos'),
  ('International Day of Awareness of the Special Development Needs and Challenges of Landlocked Developing Countries', 'Dia Internacional de Conscientização sobre as Necessidades e os Desafios dos Países em Desenvolvimento sem Litoral'),
  ('International Day of Cooperatives', 'Dia Internacional das Cooperativas'),
  ('International Day of Deafblindness', 'Dia Internacional da Surdocegueira'),
  ('International Day of Forests [FAO]', 'Dia Internacional das Florestas'),
  ('International Day of Hope', 'Dia Internacional da Esperança'),
  ('International Day of Peaceful Coexistence', 'Dia Internacional da Coexistência Pacífica'),
  ('International Day of the World’s Indigenous Women and Girls', 'Dia Internacional das Mulheres e Meninas Indígenas'),
  ('International Girls in ICT Day [ITU]', 'Dia Internacional das Meninas nas TIC'),
  ('International Wellness Day', 'Dia Internacional do Bem-Estar'),
  ('World Day for Glaciers', 'Dia Mundial das Geleiras'),
  ('World Day of Remembrance for Road Traffic Victims', 'Dia Mundial em Memória das Vítimas de Trânsito'),
  ('World Habitat Day', 'Dia Mundial do Habitat'),
  ('World Horse Day', 'Dia Mundial do Cavalo'),
  ('World Maritime Day', 'Dia Marítimo Mundial'),
  ('World Migratory Bird Day [UNEP]', 'Dia Mundial das Aves Migratórias'),
  ('World Rural Development Day', 'Dia Mundial do Desenvolvimento Rural')
)
update public.oportunidades o
   set nome = t.pt,
       aliases = case when t.en = any(coalesce(o.aliases, '{}'::text[])) then o.aliases
                      else coalesce(o.aliases, '{}'::text[]) || t.en end,
       atualizado_em = now()
  from t
 where o.nome = t.en and o.ativo;
