-- =====================================================================
-- ORDEM DAS MIGRATIONS
--
-- Este arquivo NÃO executa nada: o SQL Editor do Supabase roda um script
-- por vez, e juntar tudo num só esconderia qual etapa falhou.
--
-- Rode os arquivos abaixo, nesta ordem, um de cada vez. Todos são
-- aditivos e idempotentes: repetir não causa dano.
--
--   1. migration_vnext.sql        estrutura base
--   2. migration_vcontent.sql     conteúdos e linha editorial
--   3. migration_semana.sql       status semanal
--   4. migration_central.sql      central de produção + correção da view
--   5. migration_auth.sql         perfis, vínculos e autorização
--   6. migration_portal.sql       aprovações, comentários e avatar
--   7. migration_kanban.sql       quadro de produção
--   8. migration_fix.sql          correções da revisão de 09/09/2026
--   9. migration_aprovacoes_v2.sql aprovações transacionais, eventos,
--                                 notificações e Kanban automático
--                                 (ver APROVACOES.md)
--  10. migration_pilares.sql     pilares de conteúdo (conteudos.pilar_id)
--  11. migration_presenca.sql    preferências, last_login_at/last_seen_at,
--                                 heartbeat; recria minha_sessao
--  12. migration_push.sql        push_subscricoes + publicação Realtime
--                                 (ver PUSH.md)
--  13. migration_aprovacoes_v3.sql "Excluir aprovação": anulação auditada
--                                 pelo Admin, evento aprovacao.anulada,
--                                 kanban_demandas.aviso (ver APROVACOES.md)
--  14. migration_kanban_v2.sql   Kanban 2.0: vínculo ativo único (com
--                                 diagnóstico de duplicatas), kanban_resumo
--                                 com ajustes pendentes, kanban_mover,
--                                 ajuste por cena → coluna Ajustes,
--                                 kanban_* na publicação Realtime
--  15. migration_portal_v2.sql   portal do cliente: views portal_producao,
--                                 portal_gravacoes, portal_status;
--                                 gravacoes.visivel_cliente; minha_sessao
--
--  16. migration_rls.sql         só depois de:
--                                 - conseguir entrar como admin
--                                 - existir um usuário cliente de teste
--                                 - ter migration_rls_reverter.sql aberto
--
--  17. migration_design.sql      B7 Design: papel designer,
--                                 deliverables/versões/arquivos, geração a
--                                 partir da Linha Editorial, revisão
--                                 interna, bucket design-files, e a
--                                 política de LEITURA do Designer sobre a
--                                 Linha Editorial (precisa que migration_rls
--                                 já tenha rodado — ela apaga e recria as
--                                 políticas das tabelas de conteúdo, e essa
--                                 política adicional tem que sobreviver por
--                                 cima). Ver CORRECOES_2026-09-09.md.
--
--  18. migration_design_refino.sql  POR ÚLTIMO. Refino operacional do B7
--                                 Design: upload deixa de ser obrigatório
--                                 (via 'upload' | 'externa' em
--                                 design_versoes), e "Assumir demanda" em
--                                 lote por Linha Editorial
--                                 (design_assumir_demanda_linha). Roda
--                                 depois de migration_design.sql. Ver
--                                 CORRECOES_2026-09-09.md, build -f.
--
--  19. migration_design_thumb.sql  Miniatura otimizada (caminho_thumb) +
--                                 colunas ultima_previa_thumb/_mime na
--                                 view design_resumo. Build -ae.
--
--  20. migration_notificacoes_deeplink.sql  Link da notificação de
--                                 "linha concluída" apontando pra rota
--                                 real (#/design/linha/:id). Build -ag.
--
--  21. migration_design_arquivos_v2.sql  Arquivos 2.0: arte por
--                                 slide/frame (parte_id estável),
--                                 dimensões, decisão de revisão por
--                                 arquivo, arquivo efetivo por parte,
--                                 envio validando completude, fechamento
--                                 de revisão agrupado. Roda depois de 19
--                                 (troca a assinatura de
--                                 design_arquivo_registrar). Build -ah.
--
--  22. migration_design_decisao_cliente.sql  Decisão do cliente
--                                 registrada pela equipe B7 (WhatsApp,
--                                 ligação…): procedência em aprovacoes,
--                                 feedback do cliente por slide, trigger
--                                 que propaga a decisão (Portal, B7 ou
--                                 anulação) pra peça, aprov_processar_evento
--                                 recriada com texto honesto + card do
--                                 Kanban da peça. Roda depois de 21 e de
--                                 migration_aprovacoes_v3.sql. Build -aj.
--
--  23. migration_status_linha_sync.sql  Status Semanal ↔ Linha
--                                 Editorial: `status_itens.situacao_auto`
--                                 (default true), `mapa_situacao_de_
--                                 conteudo()` e o gatilho
--                                 `conteudos_sync_status_itens` — a
--                                 situação de uma demanda vinda da Linha
--                                 Editorial passa a nascer e a seguir
--                                 sozinha o status do conteúdo vinculado
--                                 (Ideia/Em criação/Em revisão/Aprovado/
--                                 Programado/Publicado, traduzido pro
--                                 vocabulário do formato), até alguém
--                                 escolher a situação à mão no card.
--                                 Roda depois de migration_semana.sql.
--                                 Build -am.
--
-- Se algum arquivo reclamar de coluna ou tabela inexistente, é porque um
-- anterior não rodou. A mensagem diz qual.
-- =====================================================================

select 'Leia os comentários deste arquivo: ele lista a ordem das migrations.' as leia_me;
