-- =====================================================================
-- ORDEM DAS MIGRATIONS
--
-- Este arquivo NÃO executa nada: o SQL Editor do Supabase roda um script
-- por vez, e juntar tudo num só esconderia qual etapa falhou.
--
-- Rode os arquivos abaixo, nesta ordem, um de cada vez. Todos são
-- aditivos e idempotentes: repetir não causa dano.
--
--   1. migration_vnext.sql        estrutura base
--   2. migration_vcontent.sql     conteúdos e linha editorial
--   3. migration_semana.sql       status semanal
--   4. migration_central.sql      central de produção + correção da view
--   5. migration_auth.sql         perfis, vínculos e autorização
--   6. migration_portal.sql       aprovações, comentários e avatar
--   7. migration_kanban.sql       quadro de produção
--   8. migration_fix.sql          correções da revisão de 09/09/2026
--   9. migration_aprovacoes_v2.sql aprovações transacionais, eventos,
--                                 notificações e Kanban automático
--                                 (ver APROVACOES.md)
--  10. migration_pilares.sql     pilares de conteúdo (conteudos.pilar_id)
--  11. migration_presenca.sql    preferências, last_login_at/last_seen_at,
--                                 heartbeat; recria minha_sessao
--  12. migration_push.sql        push_subscricoes + publicação Realtime
--                                 (ver PUSH.md)
--  13. migration_aprovacoes_v3.sql "Excluir aprovação": anulação auditada
--                                 pelo Admin, evento aprovacao.anulada,
--                                 kanban_demandas.aviso (ver APROVACOES.md)
--  14. migration_kanban_v2.sql   Kanban 2.0: vínculo ativo único (com
--                                 diagnóstico de duplicatas), kanban_resumo
--                                 com ajustes pendentes, kanban_mover,
--                                 ajuste por cena → coluna Ajustes,
--                                 kanban_* na publicação Realtime
--  15. migration_portal_v2.sql   portal do cliente: views portal_producao,
--                                 portal_gravacoes, portal_status;
--                                 gravacoes.visivel_cliente; minha_sessao
--
--  16. migration_rls.sql         POR ÚLTIMO, e só depois de:
--                                 - conseguir entrar como admin
--                                 - existir um usuário cliente de teste
--                                 - ter migration_rls_reverter.sql aberto
--
-- Se algum arquivo reclamar de coluna ou tabela inexistente, é porque um
-- anterior não rodou. A mensagem diz qual.
-- =====================================================================

select 'Leia os comentários deste arquivo: ele lista a ordem das migrations.' as leia_me;
